/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v2/health-check': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Check */
    get: operations['witswin_api_health_check']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/{id}/check-referral-code/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Check Referral Code */
    post: operations['quiz_apis_competitions_api_check_referral_code']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/enroll/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Enroll To Competition */
    post: operations['quiz_apis_competitions_api_enroll_to_competition']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/enroll/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Competition Enroll */
    delete: operations['quiz_apis_competitions_api_delete_competition_enroll']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Quiz */
    get: operations['quiz_apis_competitions_api_get_quiz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Quizzes List */
    get: operations['quiz_apis_competitions_api_get_quizzes_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/demo/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Demo Quiz */
    get: operations['quiz_apis_competitions_api_get_demo_quiz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/{competition_pk}/check-constraints/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Check Requirement Api */
    post: operations['quiz_apis_competitions_api_check_requirement_api']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/quiz/competitions/sandbox/{competition_id}/reset/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Reset Sandbox Competition */
    get: operations['quiz_apis_competition_sandbox_api_reset_sandbox_competition']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/auth/telegram-login/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Telegram Auth Mini App
     * @description login with telegram through mini app
     */
    post: operations['authentication_api_telegram_login_api_telegram_auth_mini_app']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/auth/telegram-login-widget/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Telegram Widget Login
     * @description login with telegram through web with telegram login widget
     */
    post: operations['authentication_api_telegram_login_api_telegram_widget_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v2/auth/sandbox/create-dummy/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Create Dummy User */
    get: operations['authentication_api_user_sandbox_api_create_dummy_user']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ReferralValidateSchema */
    ReferralValidateSchema: {
      /** Referralcode */
      referralCode: string
    }
    /** CompetitionEnrollIn */
    CompetitionEnrollIn: {
      /** Userhints */
      userHints: number[]
      /** Referralcode */
      referralCode: string | null
      /** Competition */
      competition: number
      /** Competitiondata */
      competitionData: {
        [key: string]: unknown
      } | null
    }
    /** CompetitionHintSchema */
    CompetitionHintSchema: {
      hint: components['schemas']['HintSchema']
      /** ID */
      id?: number | null
      /**
       * Count
       * @default 1
       */
      count: number
    }
    /** CompetitionWithResourceSchema */
    CompetitionWithResourceSchema: {
      /** Questions */
      questions: components['schemas']['SmallQuestionSchema'][]
      /** Sponsors */
      sponsors: components['schemas']['SponsorSchema'][]
      /** Participantscount */
      participantsCount: number
      /** Userprofile */
      userProfile: number
      /** Builtinhints */
      builtInHints: components['schemas']['CompetitionHintSchema'][]
      /** Isfinished */
      isFinished: boolean
      /** Isvip */
      isVip: boolean
      /** Prizeamount */
      prizeAmount: number
      /** Allowedhinttypes */
      allowedHintTypes: components['schemas']['HintSchema'][]
      /** Formattedprize */
      formattedPrize: number | string
      /** Constraints */
      constraints: components['schemas']['ConstraintSchema'][]
      /** ID */
      id?: number | null
      /** Title */
      title: string
      /** Details */
      details?: string | null
      /**
       * Created At
       * Format: date-time
       */
      createdAt: string
      /** Start At */
      startAt?: string | null
      /** Chain Id */
      chainId?: number | null
      /**
       * Language
       * @default en
       */
      language: string
      /**
       * Token Decimals
       * @default 18
       */
      tokenDecimals: number | null
      /** Token */
      token?: string | null
      /** Token Address */
      tokenAddress?: string | null
      /** Discord Url */
      discordUrl?: string | null
      /** Twitter Url */
      twitterUrl?: string | null
      /** Email Url */
      emailUrl: string
      /** Telegram Url */
      telegramUrl?: string | null
      /** Token Image */
      tokenImage?: string | null
      /** Image */
      image?: string | null
      /**
       * Shuffle Answers
       * @default false
       */
      shuffleAnswers: boolean
      /**
       * Split Prize
       * @default true
       */
      splitPrize: boolean
      /**
       * Max Participants
       * @default 0
       */
      maxParticipants: number
      /**
       * Is Winners Announced
       * @default false
       */
      isWinnersAnnounced: boolean
      /** Constraint Params */
      constraintParams?: string | null
      /** Reversed Constraints */
      reversedConstraints?: string | null
      /** Referral Code */
      referralCode?: string | null
      /** Tx Hash */
      txHash?: string | null
      /**
       * Is Demo
       * @default false
       */
      isDemo: boolean
      /**
       * Is Active
       * @default true
       */
      isActive: boolean
      /**
       * Is Sandbox
       * @default false
       */
      isSandbox: boolean
      /**
       * Is Testnet
       * @default false
       */
      isTestnet: boolean
      /**
       * Lives
       * @default 1
       */
      lives: number
      /**
       * Hint Count
       * @default 1
       */
      hintCount: number
      /**
       * Question Time Seconds
       * @default 14
       */
      questionTimeSeconds: number
      /**
       * Question Hint Time Seconds
       * @default 4
       */
      questionHintTimeSeconds: number
      /**
       * Rest Time Seconds
       * @default 9
       */
      restTimeSeconds: number
      /** Announce Winners Api Url */
      announceWinnersApiUrl?: string | null
      /** Api Response */
      apiResponse?: string | null
      /** Api Error Response */
      apiErrorResponse?: string | null
      /** Resources */
      resources: components['schemas']['ResourceSchema'][]
    }
    /** ConstraintSchema */
    ConstraintSchema: {
      /** Name */
      name: string
      /** Title */
      title: string
      /** Type */
      type: string
      /** Description */
      description?: string | null
      /** Negativedescription */
      negativeDescription?: string | null
      /** Response */
      response?: string | null
      /** Iconurl */
      iconUrl?: string | null
      /** Explaination */
      explaination?: string | null
    }
    /** HintSchema */
    HintSchema: {
      /** Hint */
      hint: number
      /** ID */
      id?: number | null
      /** Hint Type */
      hintType: string
      /** Title */
      title: string
      /** Description */
      description: string
      /**
       * Is Active
       * @default true
       */
      isActive: boolean
      /** Icon */
      icon?: string | null
    }
    /** ResourceSchema */
    ResourceSchema: {
      /** ID */
      id?: number | null
      /** Title */
      title: string
      /** Content */
      content: string
      /** Link */
      link?: string | null
      /** Link Text */
      linkText?: string | null
      /** Image */
      image?: string | null
      /**
       * Created At
       * Format: date-time
       */
      createdAt: string
      /** Competition */
      competition_id?: number | null
      /**
       * Is Active
       * @default true
       */
      isActive: boolean
    }
    /** SmallQuestionSchema */
    SmallQuestionSchema: {
      /** Pk */
      pk: number
      /** Number */
      number: number
    }
    /** SponsorSchema */
    SponsorSchema: {
      /** ID */
      id?: number | null
      /** Name */
      name: string
      /** Link */
      link: string
      /** Description */
      description?: string | null
      /** Image */
      image?: string | null
    }
    /** ChoiceSchema */
    ChoiceSchema: {
      /** Iscorrect */
      isCorrect?: boolean | null
      /** Question */
      question: number
      /** ID */
      id?: number | null
      /** Text */
      text: string
    }
    /** DemoCompetitionWithResourceSchema */
    DemoCompetitionWithResourceSchema: {
      /** Questions */
      questions: components['schemas']['QuestionSchema'][]
      /** Sponsors */
      sponsors: components['schemas']['SponsorSchema'][]
      /** Participantscount */
      participantsCount: number
      /** Userprofile */
      userProfile: number
      /** Builtinhints */
      builtInHints: components['schemas']['CompetitionHintSchema'][]
      /** Isfinished */
      isFinished: boolean
      /** Isvip */
      isVip: boolean
      /** Prizeamount */
      prizeAmount: number
      /** Allowedhinttypes */
      allowedHintTypes: components['schemas']['HintSchema'][]
      /** Formattedprize */
      formattedPrize: number | string
      /** Constraints */
      constraints: components['schemas']['ConstraintSchema'][]
      /** ID */
      id?: number | null
      /** Title */
      title: string
      /** Details */
      details?: string | null
      /**
       * Created At
       * Format: date-time
       */
      createdAt: string
      /** Start At */
      startAt?: string | null
      /** Chain Id */
      chainId?: number | null
      /**
       * Language
       * @default en
       */
      language: string
      /**
       * Token Decimals
       * @default 18
       */
      tokenDecimals: number | null
      /** Token */
      token?: string | null
      /** Token Address */
      tokenAddress?: string | null
      /** Discord Url */
      discordUrl?: string | null
      /** Twitter Url */
      twitterUrl?: string | null
      /** Email Url */
      emailUrl: string
      /** Telegram Url */
      telegramUrl?: string | null
      /** Token Image */
      tokenImage?: string | null
      /** Image */
      image?: string | null
      /**
       * Shuffle Answers
       * @default false
       */
      shuffleAnswers: boolean
      /**
       * Split Prize
       * @default true
       */
      splitPrize: boolean
      /**
       * Max Participants
       * @default 0
       */
      maxParticipants: number
      /**
       * Is Winners Announced
       * @default false
       */
      isWinnersAnnounced: boolean
      /** Constraint Params */
      constraintParams?: string | null
      /** Reversed Constraints */
      reversedConstraints?: string | null
      /** Referral Code */
      referralCode?: string | null
      /** Tx Hash */
      txHash?: string | null
      /**
       * Is Demo
       * @default false
       */
      isDemo: boolean
      /**
       * Is Active
       * @default true
       */
      isActive: boolean
      /**
       * Is Sandbox
       * @default false
       */
      isSandbox: boolean
      /**
       * Is Testnet
       * @default false
       */
      isTestnet: boolean
      /**
       * Lives
       * @default 1
       */
      lives: number
      /**
       * Hint Count
       * @default 1
       */
      hintCount: number
      /**
       * Question Time Seconds
       * @default 14
       */
      questionTimeSeconds: number
      /**
       * Question Hint Time Seconds
       * @default 4
       */
      questionHintTimeSeconds: number
      /**
       * Rest Time Seconds
       * @default 9
       */
      restTimeSeconds: number
      /** Announce Winners Api Url */
      announceWinnersApiUrl?: string | null
      /** Api Response */
      apiResponse?: string | null
      /** Api Error Response */
      apiErrorResponse?: string | null
      /** Resources */
      resources: components['schemas']['ResourceSchema'][]
    }
    /** QuestionSchema */
    QuestionSchema: {
      /** Choices */
      choices: components['schemas']['ChoiceSchema'][]
      /** Competition */
      competition: number
      /** ID */
      id?: number | null
      /** Number */
      number: number
      /** Text */
      text: string
      /**
       * Creator
       * @default Wits Team
       */
      creator: string
    }
    /** CompetitionCheckConstraintSchema */
    CompetitionCheckConstraintSchema: {
      /** Competitiondata */
      competitionData: {
        [key: string]: unknown
      } | null
    }
    /** UserProfileSchema */
    UserProfileSchema: {
      /** Wallets */
      wallets: components['schemas']['WalletSchema'][]
      /** Pk */
      pk: number
      /** Username */
      username: string
      /** Neuron */
      neuron: number
      /** Token */
      token: string | null
      /** Refreshtoken */
      refreshToken: string | null
    }
    /** WalletSchema */
    WalletSchema: {
      /** Pk */
      pk: number
      /** Walletaddress */
      walletAddress: string
      /** Createdat */
      createdAt: string
    }
    /** TelegramAuthIn */
    TelegramAuthIn: {
      /** Telegramdata */
      telegramData: string
    }
    /** TelegramWidgetIn */
    TelegramWidgetIn: {
      /** Hash */
      hash: string
      /** Id */
      id: number
      /** Firstname */
      firstName: string
      /**
       * Lastname
       * @default
       */
      lastName: string | null
      /**
       * Username
       * @default
       */
      username: string | null
      /** Photourl */
      photoUrl?: string | null
      /** Authdate */
      authDate: number
      /** Birthdate */
      birthDate: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  witswin_api_health_check: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
    }
  }
  quiz_apis_competitions_api_check_referral_code: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReferralValidateSchema']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
    }
  }
  quiz_apis_competitions_api_enroll_to_competition: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompetitionEnrollIn']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  quiz_apis_competitions_api_delete_competition_enroll: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  quiz_apis_competitions_api_get_quiz: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompetitionWithResourceSchema']
        }
      }
    }
  }
  quiz_apis_competitions_api_get_quizzes_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompetitionWithResourceSchema'][]
        }
      }
    }
  }
  quiz_apis_competitions_api_get_demo_quiz: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DemoCompetitionWithResourceSchema']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
    }
  }
  quiz_apis_competitions_api_check_requirement_api: {
    parameters: {
      query?: never
      header?: never
      path: {
        competition_pk: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompetitionCheckConstraintSchema']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  quiz_apis_competition_sandbox_api_reset_sandbox_competition: {
    parameters: {
      query?: {
        minutes?: number
        seconds?: number
        hours?: number
      }
      header?: never
      path: {
        competition_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  authentication_api_telegram_login_api_telegram_auth_mini_app: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TelegramAuthIn']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserProfileSchema']
        }
      }
    }
  }
  authentication_api_telegram_login_api_telegram_widget_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TelegramWidgetIn']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserProfileSchema']
        }
      }
    }
  }
  authentication_api_user_sandbox_api_create_dummy_user: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserProfileSchema']
        }
      }
    }
  }
}
