name: Build and Deploy to NPM with Bun

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Bun (latest version)
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest' # Specify Bun version (latest here)

      # Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # Build the package with Bun
      - name: Build the package
        run: bun build # Bun's build command

      # Publish the package to npm
      - name: Publish to npm
        run: npm publish --access public # --access public is needed for public packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use NPM_TOKEN secret for authentication
