name: Build and Deploy to NPM with Bun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Build the package
        run: bun run build

      - name: Publish to npm
        run: |
          npm config set _authToken=${{secrets.NPM_TOKEN}}
          npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use NPM_TOKEN secret for authentication
